[tool.poetry]
name = "introducao"
version = "0.1.0"
description = ""
authors = ["danubiobwm"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
